/**
 * Seed 120 Tool Definitions into the database.
 * Idempotent — uses upsert so it can be run multiple times safely.
 *
 * Usage: npx tsx prisma/seed-tools.ts
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// ── Types ────────────────────────────────────────────────────────────────────

interface CredentialField {
  key: string
  label: string
  isSecret: boolean
}

interface ToolSeed {
  toolNumber: number
  name: string
  url: string
  authType: string
  requiredCredentials: string // JSON string of CredentialField[]
  connectionType: string
  category: string
  subcategory: string
  capabilities: string
  automationLevel: string
  description: string
  icon: string
  color: string
  sortOrder: number
}

// ── Helper ───────────────────────────────────────────────────────────────────

function creds(fields: CredentialField[]): string {
  return JSON.stringify(fields)
}

// ── Tool Definitions ─────────────────────────────────────────────────────────

const TOOLS: ToolSeed[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // GOOGLE (8 tools, 001–008)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 1,
    name: 'Google Search Console',
    url: 'https://search.google.com/search-console',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google',
    subcategory: 'seo',
    capabilities: 'SEO/keyword/performance data',
    automationLevel: 'LIMITED',
    description: 'Monitor, maintain, and troubleshoot your site\'s presence in Google Search results.',
    icon: 'Search',
    color: '#4285F4',
    sortOrder: 1,
  },
  {
    toolNumber: 2,
    name: 'Google Analytics 4',
    url: 'https://analytics.google.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GA4_MEASUREMENT_ID', label: 'GA4 Measurement ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google',
    subcategory: 'analytics',
    capabilities: 'Analytics/audience/events/conversions',
    automationLevel: 'LIMITED',
    description: 'Advanced web analytics to understand user behavior and measure marketing effectiveness.',
    icon: 'BarChart3',
    color: '#E37400',
    sortOrder: 2,
  },
  {
    toolNumber: 3,
    name: 'Google Business Profile',
    url: 'https://business.google.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google',
    subcategory: 'local_business',
    capabilities: 'Business listing/reviews/local SEO/insights',
    automationLevel: 'LIMITED',
    description: 'Manage your business presence on Google Search and Maps.',
    icon: 'Store',
    color: '#4285F4',
    sortOrder: 3,
  },
  {
    toolNumber: 4,
    name: 'Google Maps Platform',
    url: 'https://maps.google.com',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'GOOGLE_MAPS_API_KEY', label: 'Google Maps API Key', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google',
    subcategory: 'local_business',
    capabilities: 'Maps/embed/directions/geocoding/places',
    automationLevel: 'AUTO',
    description: 'Embed maps, get directions, and access location data for business listings.',
    icon: 'MapPin',
    color: '#34A853',
    sortOrder: 4,
  },
  {
    toolNumber: 5,
    name: 'Google Ads',
    url: 'https://ads.google.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
      { key: 'GOOGLE_DEVELOPER_TOKEN', label: 'Developer Token', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google',
    subcategory: 'paid_ads',
    capabilities: 'Search ads/display ads/campaign management/performance',
    automationLevel: 'LIMITED',
    description: 'Run and manage Google Ads campaigns including search, display, and video ads.',
    icon: 'Target',
    color: '#4285F4',
    sortOrder: 5,
  },
  {
    toolNumber: 6,
    name: 'Google Keyword Planner',
    url: 'https://ads.google.com/home/tools/keyword-planner/',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
      { key: 'GOOGLE_DEVELOPER_TOKEN', label: 'Developer Token', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google',
    subcategory: 'keyword_research',
    capabilities: 'Keyword research/search volume/bid estimates',
    automationLevel: 'AUTO',
    description: 'Discover keywords and get search volume data for SEO and PPC campaigns.',
    icon: 'Key',
    color: '#4285F4',
    sortOrder: 6,
  },
  {
    toolNumber: 7,
    name: 'YouTube Data API',
    url: 'https://developers.google.com/youtube/v3',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'YOUTUBE_API_KEY', label: 'YouTube API Key', isSecret: true },
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID (OAuth)', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret (OAuth)', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google',
    subcategory: 'video',
    capabilities: 'Video data/channels/playlists/comments/analytics',
    automationLevel: 'AUTO',
    description: 'Retrieve YouTube video, channel, and playlist data for content strategy.',
    icon: 'Youtube',
    color: '#FF0000',
    sortOrder: 7,
  },
  {
    toolNumber: 8,
    name: 'YouTube Analytics',
    url: 'https://studio.youtube.com/analytics',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google',
    subcategory: 'video_analytics',
    capabilities: 'Video performance/audience demographics/revenue',
    automationLevel: 'CHECK',
    description: 'Analyze YouTube channel and video performance with detailed metrics.',
    icon: 'BarChart2',
    color: '#FF0000',
    sortOrder: 8,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // META (7 tools, 009–015)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 9,
    name: 'Facebook Pages',
    url: 'https://developers.facebook.com/docs/pages',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'FACEBOOK_APP_ID', label: 'Facebook App ID', isSecret: false },
      { key: 'FACEBOOK_APP_SECRET', label: 'Facebook App Secret', isSecret: true },
      { key: 'FACEBOOK_PAGE_ACCESS_TOKEN', label: 'Page Access Token', isSecret: true },
    ]),
    connectionType: 'graph_api',
    category: 'meta',
    subcategory: 'organic',
    capabilities: 'Page management/posts/engagement/insights',
    automationLevel: 'LIMITED',
    description: 'Manage Facebook Page content, schedule posts, and retrieve engagement analytics.',
    icon: 'Facebook',
    color: '#1877F2',
    sortOrder: 9,
  },
  {
    toolNumber: 10,
    name: 'Facebook Lead Ads',
    url: 'https://developers.facebook.com/docs/marketing-api/leadgen',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'FACEBOOK_APP_ID', label: 'Facebook App ID', isSecret: false },
      { key: 'FACEBOOK_APP_SECRET', label: 'Facebook App Secret', isSecret: true },
      { key: 'FACEBOOK_PAGE_ACCESS_TOKEN', label: 'Page Access Token', isSecret: true },
    ]),
    connectionType: 'graph_api',
    category: 'meta',
    subcategory: 'paid_ads',
    capabilities: 'Lead generation/lead forms/lead retrieval',
    automationLevel: 'AUTO',
    description: 'Capture leads from Facebook Lead Ads campaigns and sync with CRM.',
    icon: 'UserPlus',
    color: '#1877F2',
    sortOrder: 10,
  },
  {
    toolNumber: 11,
    name: 'Facebook Ads',
    url: 'https://developers.facebook.com/docs/marketing-apis',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'FACEBOOK_APP_ID', label: 'Facebook App ID', isSecret: false },
      { key: 'FACEBOOK_APP_SECRET', label: 'Facebook App Secret', isSecret: true },
      { key: 'FACEBOOK_AD_ACCOUNT_ID', label: 'Ad Account ID', isSecret: false },
      { key: 'FACEBOOK_ACCESS_TOKEN', label: 'Access Token', isSecret: true },
    ]),
    connectionType: 'graph_api',
    category: 'meta',
    subcategory: 'paid_ads',
    capabilities: 'Ad creation/campaign management/audience targeting/reporting',
    automationLevel: 'LIMITED',
    description: 'Create and manage Facebook advertising campaigns with the Marketing API.',
    icon: 'Megaphone',
    color: '#1877F2',
    sortOrder: 11,
  },
  {
    toolNumber: 12,
    name: 'Facebook Page Webhooks',
    url: 'https://developers.facebook.com/docs/graph-api/webhooks',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'FACEBOOK_APP_ID', label: 'Facebook App ID', isSecret: false },
      { key: 'FACEBOOK_APP_SECRET', label: 'Facebook App Secret', isSecret: true },
      { key: 'FACEBOOK_VERIFY_TOKEN', label: 'Webhook Verify Token', isSecret: true },
    ]),
    connectionType: 'webhook',
    category: 'meta',
    subcategory: 'webhooks',
    capabilities: 'Real-time events/messaging/webhook subscriptions',
    automationLevel: 'AUTO',
    description: 'Receive real-time notifications for Facebook Page events via webhooks.',
    icon: 'Webhook',
    color: '#1877F2',
    sortOrder: 12,
  },
  {
    toolNumber: 13,
    name: 'Instagram Business',
    url: 'https://developers.facebook.com/docs/instagram-api',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'FACEBOOK_APP_ID', label: 'Facebook App ID', isSecret: false },
      { key: 'FACEBOOK_APP_SECRET', label: 'Facebook App Secret', isSecret: true },
      { key: 'INSTAGRAM_BUSINESS_ACCOUNT_ID', label: 'Instagram Business Account ID', isSecret: false },
      { key: 'FACEBOOK_ACCESS_TOKEN', label: 'Access Token', isSecret: true },
    ]),
    connectionType: 'graph_api',
    category: 'meta',
    subcategory: 'organic',
    capabilities: 'Business insights/audience/media/analytics',
    automationLevel: 'LIMITED',
    description: 'Access Instagram Business account insights, media, and audience data.',
    icon: 'Instagram',
    color: '#E4405F',
    sortOrder: 13,
  },
  {
    toolNumber: 14,
    name: 'Instagram Content Publishing',
    url: 'https://developers.facebook.com/docs/instagram-api/guides/content-publishing',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'FACEBOOK_APP_ID', label: 'Facebook App ID', isSecret: false },
      { key: 'FACEBOOK_APP_SECRET', label: 'Facebook App Secret', isSecret: true },
      { key: 'INSTAGRAM_BUSINESS_ACCOUNT_ID', label: 'Instagram Business Account ID', isSecret: false },
      { key: 'FACEBOOK_ACCESS_TOKEN', label: 'Access Token', isSecret: true },
    ]),
    connectionType: 'graph_api',
    category: 'meta',
    subcategory: 'content_publishing',
    capabilities: 'Content publishing/media upload/stories/reels',
    automationLevel: 'LIMITED',
    description: 'Publish content, stories, and reels to Instagram Business accounts programmatically.',
    icon: 'ImagePlus',
    color: '#E4405F',
    sortOrder: 14,
  },
  {
    toolNumber: 15,
    name: 'Instagram Messaging',
    url: 'https://developers.facebook.com/docs/instagram-api/guides/messaging',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'FACEBOOK_APP_ID', label: 'Facebook App ID', isSecret: false },
      { key: 'FACEBOOK_APP_SECRET', label: 'Facebook App Secret', isSecret: true },
      { key: 'FACEBOOK_PAGE_ACCESS_TOKEN', label: 'Page Access Token', isSecret: true },
    ]),
    connectionType: 'graph_api',
    category: 'meta',
    subcategory: 'messaging',
    capabilities: 'Direct messages/conversations/automated replies',
    automationLevel: 'AUTO',
    description: 'Send and receive Instagram Direct Messages for customer engagement.',
    icon: 'MessageCircle',
    color: '#E4405F',
    sortOrder: 15,
  },
  {
    toolNumber: 19,
    name: 'TikTok',
    url: 'https://developers.tiktok.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'TIKTOK_CLIENT_KEY', label: 'TikTok Client Key', isSecret: false },
      { key: 'TIKTOK_CLIENT_SECRET', label: 'TikTok Client Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'tiktok',
    subcategory: 'social',
    capabilities: 'Social content/analytics/user data/trending',
    automationLevel: 'LIMITED',
    description: 'Access TikTok content, analytics, and user data via the TikTok API.',
    icon: 'Music',
    color: '#000000',
    sortOrder: 19,
  },
  {
    toolNumber: 20,
    name: 'TikTok Content Posting',
    url: 'https://developers.tiktok.com/doc/content-posting-api',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'TIKTOK_CLIENT_KEY', label: 'TikTok Client Key', isSecret: false },
      { key: 'TIKTOK_CLIENT_SECRET', label: 'TikTok Client Secret', isSecret: true },
      { key: 'TIKTOK_ACCESS_TOKEN', label: 'TikTok Access Token', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'tiktok',
    subcategory: 'content_publishing',
    capabilities: 'Video upload/content publishing/draft management',
    automationLevel: 'LIMITED',
    description: 'Upload and publish video content to TikTok accounts programmatically.',
    icon: 'Upload',
    color: '#000000',
    sortOrder: 20,
  },
  {
    toolNumber: 21,
    name: 'TikTok Lead Generation',
    url: 'https://ads.tiktok.com',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'TIKTOK_CLIENT_KEY', label: 'TikTok Client Key', isSecret: false },
      { key: 'TIKTOK_CLIENT_SECRET', label: 'TikTok Client Secret', isSecret: true },
      { key: 'TIKTOK_ADVERTISER_ID', label: 'Advertiser ID', isSecret: false },
    ]),
    connectionType: 'api',
    category: 'tiktok',
    subcategory: 'paid_ads',
    capabilities: 'Lead generation/lead forms/campaign targeting',
    automationLevel: 'LIMITED',
    description: 'Generate and capture leads through TikTok advertising campaigns.',
    icon: 'Users',
    color: '#000000',
    sortOrder: 21,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LINKEDIN (3 tools, 022–024)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 22,
    name: 'LinkedIn Company Page',
    url: 'https://developers.linkedin.com/docs/company-pages',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'LINKEDIN_CLIENT_ID', label: 'LinkedIn Client ID', isSecret: false },
      { key: 'LINKEDIN_CLIENT_SECRET', label: 'LinkedIn Client Secret', isSecret: true },
      { key: 'LINKEDIN_ACCESS_TOKEN', label: 'LinkedIn Access Token', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'linkedin',
    subcategory: 'organic',
    capabilities: 'Company page/posts/follower analytics/engagement',
    automationLevel: 'LIMITED',
    description: 'Manage LinkedIn Company Page content and retrieve follower analytics.',
    icon: 'Linkedin',
    color: '#0A66C2',
    sortOrder: 22,
  },
  {
    toolNumber: 23,
    name: 'LinkedIn Marketing',
    url: 'https://developers.linkedin.com/docs/marketing',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'LINKEDIN_CLIENT_ID', label: 'LinkedIn Client ID', isSecret: false },
      { key: 'LINKEDIN_CLIENT_SECRET', label: 'LinkedIn Client Secret', isSecret: true },
      { key: 'LINKEDIN_ACCESS_TOKEN', label: 'LinkedIn Access Token', isSecret: true },
      { key: 'LINKEDIN_AD_ACCOUNT_ID', label: 'Ad Account ID', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'linkedin',
    subcategory: 'marketing',
    capabilities: 'Ad campaigns/audience targeting/Sponsored Content/InMail',
    automationLevel: 'LIMITED',
    description: 'Run LinkedIn advertising campaigns including Sponsored Content and InMail ads.',
    icon: 'Briefcase',
    color: '#0A66C2',
    sortOrder: 23,
  },
  {
    toolNumber: 24,
    name: 'LinkedIn Lead Gen Forms',
    url: 'https://developers.linkedin.com/docs/marketing/lead-gen-forms',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'LINKEDIN_CLIENT_ID', label: 'LinkedIn Client ID', isSecret: false },
      { key: 'LINKEDIN_CLIENT_SECRET', label: 'LinkedIn Client Secret', isSecret: true },
      { key: 'LINKEDIN_ACCESS_TOKEN', label: 'LinkedIn Access Token', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'linkedin',
    subcategory: 'lead_generation',
    capabilities: 'Lead forms/lead retrieval/CRM integration',
    automationLevel: 'AUTO',
    description: 'Collect leads via LinkedIn Lead Gen Forms and sync with your CRM.',
    icon: 'FileText',
    color: '#0A66C2',
    sortOrder: 24,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // REDDIT (4 tools, 025–028)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 25,
    name: 'Reddit',
    url: 'https://www.reddit.com/dev/api',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'REDDIT_CLIENT_ID', label: 'Reddit Client ID', isSecret: false },
      { key: 'REDDIT_CLIENT_SECRET', label: 'Reddit Client Secret', isSecret: true },
      { key: 'REDDIT_USER_AGENT', label: 'User Agent', isSecret: false },
    ]),
    connectionType: 'api',
    category: 'reddit',
    subcategory: 'community',
    capabilities: 'Community management/posts/comments/subreddit monitoring',
    automationLevel: 'LIMITED',
    description: 'Interact with Reddit communities, monitor mentions, and manage posts.',
    icon: 'MessageSquare',
    color: '#FF4500',
    sortOrder: 25,
  },
  {
    toolNumber: 26,
    name: 'Reddit r/bangladesh',
    url: 'https://www.reddit.com/r/bangladesh',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'REDDIT_CLIENT_ID', label: 'Reddit Client ID', isSecret: false },
      { key: 'REDDIT_CLIENT_SECRET', label: 'Reddit Client Secret', isSecret: true },
      { key: 'REDDIT_USER_AGENT', label: 'User Agent', isSecret: false },
    ]),
    connectionType: 'api',
    category: 'reddit',
    subcategory: 'community_monitoring',
    capabilities: 'r/bangladesh monitoring/post tracking/engagement analysis',
    automationLevel: 'AUTO',
    description: 'Monitor and engage with the r/bangladesh subreddit community.',
    icon: 'MessageSquare',
    color: '#FF4500',
    sortOrder: 26,
  },
  {
    toolNumber: 27,
    name: 'Reddit r/studyAbroad',
    url: 'https://www.reddit.com/r/studyAbroad',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'REDDIT_CLIENT_ID', label: 'Reddit Client ID', isSecret: false },
      { key: 'REDDIT_CLIENT_SECRET', label: 'Reddit Client Secret', isSecret: true },
      { key: 'REDDIT_USER_AGENT', label: 'User Agent', isSecret: false },
    ]),
    connectionType: 'api',
    category: 'reddit',
    subcategory: 'community_monitoring',
    capabilities: 'r/studyAbroad monitoring/student intent detection/lead identification',
    automationLevel: 'AUTO',
    description: 'Monitor the r/studyAbroad subreddit for student leads and study abroad discussions.',
    icon: 'MessageSquare',
    color: '#FF4500',
    sortOrder: 27,
  },
  {
    toolNumber: 28,
    name: 'Reddit r/IELTS',
    url: 'https://www.reddit.com/r/IELTS',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'REDDIT_CLIENT_ID', label: 'Reddit Client ID', isSecret: false },
      { key: 'REDDIT_CLIENT_SECRET', label: 'Reddit Client Secret', isSecret: true },
      { key: 'REDDIT_USER_AGENT', label: 'User Agent', isSecret: false },
    ]),
    connectionType: 'api',
    category: 'reddit',
    subcategory: 'community_monitoring',
    capabilities: 'r/IELTS monitoring/test preparation content/student engagement',
    automationLevel: 'AUTO',
    description: 'Monitor the r/IELTS subreddit for student discussions and engagement opportunities.',
    icon: 'MessageSquare',
    color: '#FF4500',
    sortOrder: 28,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TELEGRAM (3 tools, 029–031)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 29,
    name: 'Telegram Bot',
    url: 'https://core.telegram.org/bots/api',
    authType: 'bot_token',
    requiredCredentials: creds([
      { key: 'TELEGRAM_BOT_TOKEN', label: 'Telegram Bot Token', isSecret: true },
    ]),
    connectionType: 'bot_api',
    category: 'telegram',
    subcategory: 'messaging',
    capabilities: 'Message sending/bot commands/inline keyboards/callbacks',
    automationLevel: 'AUTO',
    description: 'Send and receive messages via Telegram Bot API.',
    icon: 'Send',
    color: '#0088CC',
    sortOrder: 29,
  },
  {
    toolNumber: 30,
    name: 'Telegram Groups',
    url: 'https://core.telegram.org/bots/api',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'TELEGRAM_BOT_TOKEN', label: 'Telegram Bot Token', isSecret: true },
      { key: 'TELEGRAM_API_ID', label: 'Telegram API ID', isSecret: false },
      { key: 'TELEGRAM_API_HASH', label: 'Telegram API Hash', isSecret: true },
    ]),
    connectionType: 'bot_api',
    category: 'telegram',
    subcategory: 'community',
    capabilities: 'Group management/member analytics/mass messaging',
    automationLevel: 'AUTO',
    description: 'Manage Telegram groups, monitor member activity, and send mass messages.',
    icon: 'Users',
    color: '#0088CC',
    sortOrder: 30,
  },
  {
    toolNumber: 31,
    name: 'Telegram Channels',
    url: 'https://core.telegram.org/bots/api',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'TELEGRAM_BOT_TOKEN', label: 'Telegram Bot Token', isSecret: true },
    ]),
    connectionType: 'bot_api',
    category: 'telegram',
    subcategory: 'content_distribution',
    capabilities: 'Channel broadcasting/content distribution/subscriber analytics',
    automationLevel: 'AUTO',
    description: 'Broadcast content to Telegram channels and track subscriber engagement.',
    icon: 'Radio',
    color: '#0088CC',
    sortOrder: 31,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DISCORD (2 tools, 032–033)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 32,
    name: 'Discord',
    url: 'https://discord.com/developers/docs',
    authType: 'bot_token',
    requiredCredentials: creds([
      { key: 'DISCORD_BOT_TOKEN', label: 'Discord Bot Token', isSecret: true },
      { key: 'DISCORD_CLIENT_ID', label: 'Discord Client ID', isSecret: false },
      { key: 'DISCORD_CLIENT_SECRET', label: 'Discord Client Secret', isSecret: true },
    ]),
    connectionType: 'bot_api',
    category: 'discord',
    subcategory: 'community',
    capabilities: 'Server management/channels/roles/messages/guilds',
    automationLevel: 'AUTO',
    description: 'Manage Discord servers, channels, roles, and messages via bot API.',
    icon: 'Headphones',
    color: '#5865F2',
    sortOrder: 32,
  },
  {
    toolNumber: 33,
    name: 'Discord OAuth',
    url: 'https://discord.com/developers/docs/topics/oauth2',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'DISCORD_CLIENT_ID', label: 'Discord Client ID', isSecret: false },
      { key: 'DISCORD_CLIENT_SECRET', label: 'Discord Client Secret', isSecret: true },
    ]),
    connectionType: 'oauth2',
    category: 'discord',
    subcategory: 'authentication',
    capabilities: 'User authentication/guild join/server access',
    automationLevel: 'AUTO',
    description: 'Authenticate users via Discord OAuth2 and access guild information.',
    icon: 'Shield',
    color: '#5865F2',
    sortOrder: 33,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // X/TWITTER (2 tools, 034–035)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 34,
    name: 'X/Twitter',
    url: 'https://developer.x.com/en/docs',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'TWITTER_API_KEY', label: 'X API Key', isSecret: true },
      { key: 'TWITTER_API_SECRET', label: 'X API Secret', isSecret: true },
      { key: 'TWITTER_ACCESS_TOKEN', label: 'X Access Token', isSecret: true },
      { key: 'TWITTER_ACCESS_SECRET', label: 'X Access Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'twitter',
    subcategory: 'social_monitoring',
    capabilities: 'Tweets/timelines/user data/social monitoring',
    automationLevel: 'LIMITED',
    description: 'Access X/Twitter data including tweets, timelines, and user information.',
    icon: 'Twitter',
    color: '#000000',
    sortOrder: 34,
  },
  {
    toolNumber: 35,
    name: 'X API',
    url: 'https://developer.x.com/en/portal/dashboard',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'TWITTER_CLIENT_ID', label: 'X Client ID', isSecret: false },
      { key: 'TWITTER_CLIENT_SECRET', label: 'X Client Secret', isSecret: true },
      { key: 'TWITTER_BEARER_TOKEN', label: 'X Bearer Token', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'twitter',
    subcategory: 'social_monitoring',
    capabilities: 'V2 API/tweet management/streaming/analytics',
    automationLevel: 'LIMITED',
    description: 'Full X API v2 access for tweet management, streaming, and analytics.',
    icon: 'Globe',
    color: '#000000',
    sortOrder: 35,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PINTEREST (2 tools, 036–037)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 36,
    name: 'Pinterest',
    url: 'https://developers.pinterest.com/docs/api/v5',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'PINTEREST_APP_ID', label: 'Pinterest App ID', isSecret: false },
      { key: 'PINTEREST_APP_SECRET', label: 'Pinterest App Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'pinterest',
    subcategory: 'content_discovery',
    capabilities: 'Pins/boards/content discovery/analytics',
    automationLevel: 'LIMITED',
    description: 'Access Pinterest content, boards, and analytics for content discovery.',
    icon: 'Pin',
    color: '#E60023',
    sortOrder: 36,
  },
  {
    toolNumber: 37,
    name: 'Pinterest Business',
    url: 'https://business.pinterest.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'PINTEREST_APP_ID', label: 'Pinterest App ID', isSecret: false },
      { key: 'PINTEREST_APP_SECRET', label: 'Pinterest App Secret', isSecret: true },
      { key: 'PINTEREST_AD_ACCOUNT_ID', label: 'Ad Account ID', isSecret: false },
    ]),
    connectionType: 'api',
    category: 'pinterest',
    subcategory: 'marketing',
    capabilities: 'Pinterest ads/shopping/catalog/audience targeting',
    automationLevel: 'LIMITED',
    description: 'Run Pinterest advertising campaigns and manage shopping catalogs.',
    icon: 'LayoutGrid',
    color: '#E60023',
    sortOrder: 37,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CONTENT PLATFORMS (4 tools, 038–041)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 38,
    name: 'Quora',
    url: 'https://www.quora.com',
    authType: 'none',
    requiredCredentials: creds([]),
    connectionType: 'platform',
    category: 'content',
    subcategory: 'qa_content',
    capabilities: 'Q&A content/topic monitoring/answer posting',
    automationLevel: 'MANUAL',
    description: 'Engage with Q&A content on Quora for brand visibility and authority building.',
    icon: 'HelpCircle',
    color: '#B92B27',
    sortOrder: 38,
  },
  {
    toolNumber: 39,
    name: 'Medium',
    url: 'https://developers.medium.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'MEDIUM_INTEGRATION_TOKEN', label: 'Medium Integration Token', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'content',
    subcategory: 'content_seo',
    capabilities: 'Article publishing/content management/user data',
    automationLevel: 'LIMITED',
    description: 'Publish articles to Medium and manage content for SEO benefits.',
    icon: 'BookOpen',
    color: '#000000',
    sortOrder: 39,
  },
  {
    toolNumber: 40,
    name: 'WordPress',
    url: 'https://developer.wordpress.org/rest-api',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'WORDPRESS_APP_PASSWORD', label: 'WordPress Application Password', isSecret: true },
      { key: 'WORDPRESS_SITE_URL', label: 'WordPress Site URL', isSecret: false },
      { key: 'WORDPRESS_USERNAME', label: 'WordPress Username', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'content',
    subcategory: 'content_seo',
    capabilities: 'Blog publishing/page management/SEO/plugins',
    automationLevel: 'AUTO',
    description: 'Manage WordPress sites including posts, pages, and SEO settings.',
    icon: 'Globe',
    color: '#21759B',
    sortOrder: 40,
  },
  {
    toolNumber: 41,
    name: 'Blogger',
    url: 'https://developers.google.com/blogger/docs/3.0/reference',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
      { key: 'BLOGGER_API_KEY', label: 'Blogger API Key', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'content',
    subcategory: 'content_seo',
    capabilities: 'Blog publishing/post management/SEO/content syndication',
    automationLevel: 'LIMITED',
    description: 'Publish and manage blog posts on Google Blogger platform.',
    icon: 'PenTool',
    color: '#FF5722',
    sortOrder: 41,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BD PLATFORMS (4 tools, 042–045)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 42,
    name: 'ConsultancyCheck',
    url: 'https://www.consultancycheck.com',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'CONSULTANCYCHECK_PARTNER_KEY', label: 'Partner API Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'bd_platform',
    subcategory: 'consultancy',
    capabilities: 'Consultancy listing/rating/review management',
    automationLevel: 'PARTNER',
    description: 'Manage consultancy listings and reviews on ConsultancyCheck platform.',
    icon: 'ClipboardCheck',
    color: '#6366F1',
    sortOrder: 42,
  },
  {
    toolNumber: 43,
    name: 'StudyAbroadLists',
    url: 'https://www.studyabroadlists.com',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'STUDYABROADLISTS_PARTNER_KEY', label: 'Partner API Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'bd_platform',
    subcategory: 'agent_directory',
    capabilities: 'Agent directory listing/profile management/lead generation',
    automationLevel: 'PARTNER',
    description: 'List consultancy services in the StudyAbroadLists agent directory.',
    icon: 'List',
    color: '#8B5CF6',
    sortOrder: 43,
  },
  {
    toolNumber: 44,
    name: 'BDStudents',
    url: 'https://www.bdstudents.com',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'BDSTUDENTS_PARTNER_KEY', label: 'Partner API Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'bd_platform',
    subcategory: 'student_community',
    capabilities: 'Student community access/content promotion/engagement',
    automationLevel: 'PARTNER',
    description: 'Access and engage with the BDStudents student community platform.',
    icon: 'GraduationCap',
    color: '#EC4899',
    sortOrder: 44,
  },
  {
    toolNumber: 45,
    name: 'Lokkhyo Campus',
    url: 'https://www.lokkhyocampus.com',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'LOKKHYO_PARTNER_KEY', label: 'Partner API Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'bd_platform',
    subcategory: 'student_community',
    capabilities: 'Student community/university listing/content distribution',
    automationLevel: 'PARTNER',
    description: 'Access Lokkhyo Campus student community for university promotion and outreach.',
    icon: 'School',
    color: '#14B8A6',
    sortOrder: 45,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SCHOLARSHIPS (6 tools, 046–051)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 46,
    name: 'Chevening',
    url: 'https://www.chevening.org',
    authType: 'none',
    requiredCredentials: creds([]),
    connectionType: 'platform',
    category: 'scholarship',
    subcategory: 'scholarship_content',
    capabilities: 'Scholarship listings/deadlines/eligibility/content',
    automationLevel: 'CHECK',
    description: 'Monitor Chevening Scholarship listings, deadlines, and eligibility requirements.',
    icon: 'Award',
    color: '#DC2626',
    sortOrder: 46,
  },
  {
    toolNumber: 47,
    name: 'DAAD',
    url: 'https://www.daad.de',
    authType: 'none',
    requiredCredentials: creds([]),
    connectionType: 'platform',
    category: 'scholarship',
    subcategory: 'scholarship_content',
    capabilities: 'German scholarship listings/program database/content',
    automationLevel: 'CHECK',
    description: 'Access DAAD scholarship database for German study programs and funding.',
    icon: 'Award',
    color: '#003366',
    sortOrder: 47,
  },
  {
    toolNumber: 48,
    name: 'Erasmus+',
    url: 'https://erasmus-plus.ec.europa.eu',
    authType: 'none',
    requiredCredentials: creds([]),
    connectionType: 'platform',
    category: 'scholarship',
    subcategory: 'scholarship_content',
    capabilities: 'EU scholarship/exchange programs/deadlines/content',
    automationLevel: 'CHECK',
    description: 'Monitor Erasmus+ scholarship and exchange program opportunities.',
    icon: 'Award',
    color: '#003399',
    sortOrder: 48,
  },
  {
    toolNumber: 49,
    name: 'Commonwealth Scholarships',
    url: 'https://cscuk.fcdo.gov.uk',
    authType: 'none',
    requiredCredentials: creds([]),
    connectionType: 'platform',
    category: 'scholarship',
    subcategory: 'scholarship_content',
    capabilities: 'Commonwealth scholarship listings/eligibility/deadlines',
    automationLevel: 'CHECK',
    description: 'Track Commonwealth Scholarship opportunities for Commonwealth countries.',
    icon: 'Award',
    color: '#C8102E',
    sortOrder: 49,
  },
  {
    toolNumber: 50,
    name: 'MEXT',
    url: 'https://www.studyinjapan.go.jp/en',
    authType: 'none',
    requiredCredentials: creds([]),
    connectionType: 'platform',
    category: 'scholarship',
    subcategory: 'scholarship_content',
    capabilities: 'Japanese MEXT scholarship/program info/deadlines',
    automationLevel: 'CHECK',
    description: 'Monitor MEXT (Monbukagakusho) Japanese Government Scholarship opportunities.',
    icon: 'Award',
    color: '#BC002D',
    sortOrder: 50,
  },
  {
    toolNumber: 51,
    name: 'Study in Korea',
    url: 'https://www.studyinkorea.go.kr',
    authType: 'none',
    requiredCredentials: creds([]),
    connectionType: 'platform',
    category: 'scholarship',
    subcategory: 'scholarship_content',
    capabilities: 'Korean scholarship listings/university programs/GKS',
    automationLevel: 'CHECK',
    description: 'Monitor Korean Government Scholarship Program (GKS) and study opportunities.',
    icon: 'Award',
    color: '#003478',
    sortOrder: 51,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UNIVERSITY NETWORKS (12 tools, 052–063)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 52,
    name: 'UK University Network',
    url: 'https://www.ucas.com',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'UK_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'University recruitment/partner programs/student referrals',
    automationLevel: 'PARTNER',
    description: 'Access UK university recruitment networks and partner programs via UCAS and direct partnerships.',
    icon: 'Building2',
    color: '#012169',
    sortOrder: 52,
  },
  {
    toolNumber: 53,
    name: 'Netherlands University Network',
    url: 'https://www.studyinholland.nl',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'NL_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'Dutch university recruitment/partner programs/student referrals',
    automationLevel: 'PARTNER',
    description: 'Access Netherlands university networks for student recruitment partnerships.',
    icon: 'Building2',
    color: '#FF6600',
    sortOrder: 53,
  },
  {
    toolNumber: 54,
    name: 'Australia University Network',
    url: 'https://www.studyaustralia.gov.au',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'AU_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'Australian university recruitment/agent partnerships/student referrals',
    automationLevel: 'PARTNER',
    description: 'Access Australian university recruitment networks and agent partnerships.',
    icon: 'Building2',
    color: '#00008B',
    sortOrder: 54,
  },
  {
    toolNumber: 55,
    name: 'Canada University Network',
    url: 'https://www.educanada.ca',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'CA_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'Canadian university recruitment/Designated Learning Institutions/referrals',
    automationLevel: 'PARTNER',
    description: 'Access Canadian university networks and DLI partner programs for recruitment.',
    icon: 'Building2',
    color: '#FF0000',
    sortOrder: 55,
  },
  {
    toolNumber: 56,
    name: 'Germany University Network',
    url: 'https://www.daad.de/en',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'DE_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'German university recruitment/uni-assist/partner programs',
    automationLevel: 'PARTNER',
    description: 'Access German university networks via DAAD and uni-assist partnerships.',
    icon: 'Building2',
    color: '#DD0000',
    sortOrder: 56,
  },
  {
    toolNumber: 57,
    name: 'Finland University Network',
    url: 'https://www.studyinfo.fi',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'FI_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'Finnish university recruitment/joint application/student referrals',
    automationLevel: 'PARTNER',
    description: 'Access Finnish university networks and joint application system for recruitment.',
    icon: 'Building2',
    color: '#003580',
    sortOrder: 57,
  },
  {
    toolNumber: 58,
    name: 'Sweden University Network',
    url: 'https://www.universityadmissions.se',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'SE_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'Swedish university recruitment/universityadmissions.se/partnerships',
    automationLevel: 'PARTNER',
    description: 'Access Swedish university networks via universityadmissions.se for recruitment.',
    icon: 'Building2',
    color: '#006AA7',
    sortOrder: 58,
  },
  {
    toolNumber: 59,
    name: 'Ireland University Network',
    url: 'https://www.ucas.ie',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'IE_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'Irish university recruitment/CAO/partner programs/student referrals',
    automationLevel: 'PARTNER',
    description: 'Access Irish university networks via CAO and direct institutional partnerships.',
    icon: 'Building2',
    color: '#169B62',
    sortOrder: 59,
  },
  {
    toolNumber: 60,
    name: 'USA University Network',
    url: 'https://www.commonapp.org',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'US_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'US university recruitment/Common App/partner programs/student referrals',
    automationLevel: 'PARTNER',
    description: 'Access US university recruitment networks via Common App and direct partnerships.',
    icon: 'Building2',
    color: '#3C3B6E',
    sortOrder: 60,
  },
  {
    toolNumber: 61,
    name: 'New Zealand University Network',
    url: 'https://www.studylink.govt.nz',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'NZ_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'NZ university recruitment/education agents/student referrals',
    automationLevel: 'PARTNER',
    description: 'Access New Zealand university networks and education agent partnerships.',
    icon: 'Building2',
    color: '#000000',
    sortOrder: 61,
  },
  {
    toolNumber: 62,
    name: 'Malaysia University Network',
    url: 'https://www.mohe.gov.my',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'MY_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'Malaysian university recruitment/MQA/partner programs/student referrals',
    automationLevel: 'PARTNER',
    description: 'Access Malaysian university networks and MQA-accredited institution partnerships.',
    icon: 'Building2',
    color: '#010066',
    sortOrder: 62,
  },
  {
    toolNumber: 63,
    name: 'Japan University Network',
    url: 'https://www.studyinjapan.go.jp/en',
    authType: 'partner',
    requiredCredentials: creds([
      { key: 'JP_UNIVERSITY_PARTNER_KEY', label: 'Partner Access Key', isSecret: true },
    ]),
    connectionType: 'partner_api',
    category: 'university',
    subcategory: 'recruitment',
    capabilities: 'Japanese university recruitment/JASSO/partner programs/student referrals',
    automationLevel: 'PARTNER',
    description: 'Access Japanese university networks via JASSO and direct institutional partnerships.',
    icon: 'Building2',
    color: '#BC002D',
    sortOrder: 63,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GOOGLE WORKSPACE (5 tools, 064–068)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 64,
    name: 'Google Forms',
    url: 'https://forms.google.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google_workspace',
    subcategory: 'forms',
    capabilities: 'Form creation/response collection/data export/lead forms',
    automationLevel: 'AUTO',
    description: 'Create and manage Google Forms for lead capture and surveys.',
    icon: 'FileInput',
    color: '#4285F4',
    sortOrder: 64,
  },
  {
    toolNumber: 65,
    name: 'Google Sheets',
    url: 'https://sheets.google.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google_workspace',
    subcategory: 'data_management',
    capabilities: 'Spreadsheet data/crud operations/formulas/pivot tables',
    automationLevel: 'AUTO',
    description: 'Read, write, and manipulate Google Sheets data for reporting and data management.',
    icon: 'Table',
    color: '#34A853',
    sortOrder: 65,
  },
  {
    toolNumber: 66,
    name: 'Google Drive',
    url: 'https://drive.google.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google_workspace',
    subcategory: 'documents',
    capabilities: 'File storage/sharing/collaboration/document management',
    automationLevel: 'AUTO',
    description: 'Manage files and documents in Google Drive including upload, share, and organize.',
    icon: 'Folder',
    color: '#4285F4',
    sortOrder: 66,
  },
  {
    toolNumber: 67,
    name: 'Google Calendar',
    url: 'https://calendar.google.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google_workspace',
    subcategory: 'scheduling',
    capabilities: 'Calendar events/scheduling/availability/reminders',
    automationLevel: 'AUTO',
    description: 'Manage Google Calendar events, scheduling, and availability.',
    icon: 'Calendar',
    color: '#4285F4',
    sortOrder: 67,
  },
  {
    toolNumber: 68,
    name: 'Gmail',
    url: 'https://mail.google.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'google_workspace',
    subcategory: 'email',
    capabilities: 'Email send/receive/labels/filters/thread management',
    automationLevel: 'AUTO',
    description: 'Send, receive, and manage emails via the Gmail API.',
    icon: 'Mail',
    color: '#EA4335',
    sortOrder: 68,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MICROSOFT (4 tools, 069–072)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 69,
    name: 'Microsoft Forms',
    url: 'https://forms.office.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'MS_CLIENT_ID', label: 'Microsoft Client ID', isSecret: false },
      { key: 'MS_CLIENT_SECRET', label: 'Microsoft Client Secret', isSecret: true },
      { key: 'MS_TENANT_ID', label: 'Microsoft Tenant ID', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'microsoft',
    subcategory: 'forms',
    capabilities: 'Form creation/response collection/quiz/proctoring',
    automationLevel: 'AUTO',
    description: 'Create and manage Microsoft Forms for surveys, quizzes, and lead capture.',
    icon: 'FileInput',
    color: '#0078D4',
    sortOrder: 69,
  },
  {
    toolNumber: 70,
    name: 'Microsoft Excel',
    url: 'https://excel.office.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'MS_CLIENT_ID', label: 'Microsoft Client ID', isSecret: false },
      { key: 'MS_CLIENT_SECRET', label: 'Microsoft Client Secret', isSecret: true },
      { key: 'MS_TENANT_ID', label: 'Microsoft Tenant ID', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'microsoft',
    subcategory: 'data_management',
    capabilities: 'Spreadsheet data/crud operations/formulas/charts/Power Query',
    automationLevel: 'AUTO',
    description: 'Read and write Excel data via Microsoft Graph API.',
    icon: 'Table',
    color: '#217346',
    sortOrder: 70,
  },
  {
    toolNumber: 71,
    name: 'Microsoft Teams',
    url: 'https://teams.microsoft.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'MS_CLIENT_ID', label: 'Microsoft Client ID', isSecret: false },
      { key: 'MS_CLIENT_SECRET', label: 'Microsoft Client Secret', isSecret: true },
      { key: 'MS_TENANT_ID', label: 'Microsoft Tenant ID', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'microsoft',
    subcategory: 'communication',
    capabilities: 'Chat/channels/meetings/file sharing/app integration',
    automationLevel: 'AUTO',
    description: 'Send messages, manage channels, and handle meetings via Microsoft Teams API.',
    icon: 'Video',
    color: '#6264A7',
    sortOrder: 71,
  },
  {
    toolNumber: 72,
    name: 'Outlook',
    url: 'https://outlook.office.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'MS_CLIENT_ID', label: 'Microsoft Client ID', isSecret: false },
      { key: 'MS_CLIENT_SECRET', label: 'Microsoft Client Secret', isSecret: true },
      { key: 'MS_TENANT_ID', label: 'Microsoft Tenant ID', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'microsoft',
    subcategory: 'email',
    capabilities: 'Email send/receive/calendar/contacts/tasks',
    automationLevel: 'AUTO',
    description: 'Send, receive, and manage emails via Microsoft Outlook/Graph API.',
    icon: 'Mail',
    color: '#0078D4',
    sortOrder: 72,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // COMMUNICATION (3 tools, 073–075)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 73,
    name: 'Calendly',
    url: 'https://developer.calendly.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'CALENDLY_CLIENT_ID', label: 'Calendly Client ID', isSecret: false },
      { key: 'CALENDLY_CLIENT_SECRET', label: 'Calendly Client Secret', isSecret: true },
      { key: 'CALENDLY_PERSONAL_TOKEN', label: 'Personal Access Token', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'communication',
    subcategory: 'scheduling',
    capabilities: 'Scheduling/availability/meeting links/webhooks',
    automationLevel: 'AUTO',
    description: 'Manage scheduling, check availability, and create meeting links via Calendly API.',
    icon: 'CalendarCheck',
    color: '#006BFF',
    sortOrder: 73,
  },
  {
    toolNumber: 74,
    name: 'Zoom',
    url: 'https://developers.zoom.us/docs',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'ZOOM_CLIENT_ID', label: 'Zoom Client ID', isSecret: false },
      { key: 'ZOOM_CLIENT_SECRET', label: 'Zoom Client Secret', isSecret: true },
      { key: 'ZOOM_ACCOUNT_ID', label: 'Zoom Account ID', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'communication',
    subcategory: 'video_conferencing',
    capabilities: 'Meeting creation/management/recording/webinars',
    automationLevel: 'AUTO',
    description: 'Create and manage Zoom meetings, webinars, and recordings via the Zoom API.',
    icon: 'Video',
    color: '#2D8CFF',
    sortOrder: 74,
  },
  {
    toolNumber: 75,
    name: 'Google Meet',
    url: 'https://meet.google.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'communication',
    subcategory: 'meetings',
    capabilities: 'Meeting creation/link generation/calendar integration',
    automationLevel: 'AUTO',
    description: 'Create Google Meet links and manage meetings via Google Calendar API.',
    icon: 'Monitor',
    color: '#00897B',
    sortOrder: 75,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CRM (3 tools, 076–078)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 76,
    name: 'HubSpot',
    url: 'https://developers.hubspot.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'HUBSPOT_CLIENT_ID', label: 'HubSpot Client ID', isSecret: false },
      { key: 'HUBSPOT_CLIENT_SECRET', label: 'HubSpot Client Secret', isSecret: true },
      { key: 'HUBSPOT_ACCESS_TOKEN', label: 'HubSpot Access Token', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'crm',
    subcategory: 'crm',
    capabilities: 'CRM/contacts/deals/companies/tickets/automation',
    automationLevel: 'AUTO',
    description: 'Full HubSpot CRM integration for contact, deal, and company management.',
    icon: 'Database',
    color: '#FF7A59',
    sortOrder: 76,
  },
  {
    toolNumber: 77,
    name: 'Salesforce',
    url: 'https://developer.salesforce.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'SALESFORCE_CLIENT_ID', label: 'Salesforce Client ID', isSecret: false },
      { key: 'SALESFORCE_CLIENT_SECRET', label: 'Salesforce Client Secret', isSecret: true },
      { key: 'SALESFORCE_INSTANCE_URL', label: 'Instance URL', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'crm',
    subcategory: 'crm',
    capabilities: 'CRM/leads/opportunities/accounts/reports',
    automationLevel: 'AUTO',
    description: 'Integrate with Salesforce CRM for lead, opportunity, and account management.',
    icon: 'Cloud',
    color: '#00A1E0',
    sortOrder: 77,
  },
  {
    toolNumber: 78,
    name: 'Zoho CRM',
    url: 'https://www.zoho.com/crm/developer/docs/api/v2',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'ZOHO_CLIENT_ID', label: 'Zoho Client ID', isSecret: false },
      { key: 'ZOHO_CLIENT_SECRET', label: 'Zoho Client Secret', isSecret: true },
      { key: 'ZOHO_REFRESH_TOKEN', label: 'Zoho Refresh Token', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'crm',
    subcategory: 'crm',
    capabilities: 'CRM/leads/deals/contacts/automation/workflows',
    automationLevel: 'AUTO',
    description: 'Integrate with Zoho CRM for lead and deal management with workflow automation.',
    icon: 'Database',
    color: '#D7282D',
    sortOrder: 78,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EMAIL/SMS (4 tools, 079–082)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 79,
    name: 'Mailchimp',
    url: 'https://mailchimp.com/developer/marketing/api',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'MAILCHIMP_API_KEY', label: 'Mailchimp API Key', isSecret: true },
      { key: 'MAILCHIMP_SERVER_PREFIX', label: 'Server Prefix', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'email',
    subcategory: 'email_marketing',
    capabilities: 'Email campaigns/audience management/automation/templates',
    automationLevel: 'AUTO',
    description: 'Create and manage email marketing campaigns with Mailchimp.',
    icon: 'Mail',
    color: '#FFE01B',
    sortOrder: 79,
  },
  {
    toolNumber: 80,
    name: 'Brevo',
    url: 'https://developers.brevo.com',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'BREVO_API_KEY', label: 'Brevo API Key', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'email',
    subcategory: 'email_sms',
    capabilities: 'Email/SMS marketing/contacts/automation/transactional',
    automationLevel: 'AUTO',
    description: 'Send marketing emails, SMS, and transactional messages via Brevo (formerly Sendinblue).',
    icon: 'Send',
    color: '#1A82E2',
    sortOrder: 80,
  },
  {
    toolNumber: 81,
    name: 'Twilio',
    url: 'https://www.twilio.com/docs/usage/api',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'TWILIO_ACCOUNT_SID', label: 'Twilio Account SID', isSecret: false },
      { key: 'TWILIO_AUTH_TOKEN', label: 'Twilio Auth Token', isSecret: true },
      { key: 'TWILIO_PHONE_NUMBER', label: 'Twilio Phone Number', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'email',
    subcategory: 'sms',
    capabilities: 'SMS/Voice/verification/two-factor auth',
    automationLevel: 'AUTO',
    description: 'Send SMS and voice calls via Twilio.',
    icon: 'Smartphone',
    color: '#F22F46',
    sortOrder: 81,
  },
  {
    toolNumber: 82,
    name: 'SendGrid',
    url: 'https://docs.sendgrid.com/api-reference',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'SENDGRID_API_KEY', label: 'SendGrid API Key', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'email',
    subcategory: 'email',
    capabilities: 'Transactional email/marketing/sender verification/templates',
    automationLevel: 'AUTO',
    description: 'Send transactional and marketing emails via SendGrid API.',
    icon: 'MailCheck',
    color: '#1A82E2',
    sortOrder: 82,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // AI PROVIDERS (5 tools, 083–087)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 83,
    name: 'OpenRouter',
    url: 'https://openrouter.ai/docs',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'OPENROUTER_API_KEY', label: 'OpenRouter API Key', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'ai_provider',
    subcategory: 'ai_routing',
    capabilities: 'AI model routing/multi-provider/chat completions/embeddings',
    automationLevel: 'AUTO',
    description: 'Route AI requests to multiple LLM providers through OpenRouter.',
    icon: 'Cpu',
    color: '#000000',
    sortOrder: 83,
  },
  {
    toolNumber: 84,
    name: 'OpenAI',
    url: 'https://platform.openai.com/docs/api-reference',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'OPENAI_API_KEY', label: 'OpenAI API Key', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'ai_provider',
    subcategory: 'ai',
    capabilities: 'GPT models/chat completions/embeddings/images/assistant',
    automationLevel: 'AUTO',
    description: 'Access OpenAI GPT models for text generation, embeddings, and image creation.',
    icon: 'Brain',
    color: '#10A37F',
    sortOrder: 84,
  },
  {
    toolNumber: 85,
    name: 'Anthropic',
    url: 'https://docs.anthropic.com/en/docs/api-reference',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'ANTHROPIC_API_KEY', label: 'Anthropic API Key', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'ai_provider',
    subcategory: 'ai',
    capabilities: 'Claude models/chat completions/vision/extended thinking',
    automationLevel: 'AUTO',
    description: 'Access Anthropic Claude models for advanced AI text generation and reasoning.',
    icon: 'BrainCircuit',
    color: '#D4A574',
    sortOrder: 85,
  },
  {
    toolNumber: 86,
    name: 'Google Gemini',
    url: 'https://ai.google.dev/docs',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'GOOGLE_GEMINI_API_KEY', label: 'Google Gemini API Key', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'ai_provider',
    subcategory: 'ai',
    capabilities: 'Gemini models/chat/embeddings/vision/multimodal',
    automationLevel: 'AUTO',
    description: 'Access Google Gemini models for multimodal AI generation.',
    icon: 'Sparkles',
    color: '#4285F4',
    sortOrder: 86,
  },
  {
    toolNumber: 87,
    name: 'Groq',
    url: 'https://console.groq.com/docs',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'GROQ_API_KEY', label: 'Groq API Key', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'ai_provider',
    subcategory: 'ai',
    capabilities: 'Fast inference/LPU/chat completions/low-latency AI',
    automationLevel: 'AUTO',
    description: 'Ultra-fast AI inference via Groq LPU for real-time applications.',
    icon: 'Zap',
    color: '#F55036',
    sortOrder: 87,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PAYMENT (4 tools, 088–091)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 88,
    name: 'Stripe',
    url: 'https://stripe.com/docs/api',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'STRIPE_SECRET_KEY', label: 'Stripe Secret Key', isSecret: true },
      { key: 'STRIPE_WEBHOOK_SECRET', label: 'Stripe Webhook Secret', isSecret: true },
      { key: 'STRIPE_PUBLISHABLE_KEY', label: 'Stripe Publishable Key', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'payment',
    subcategory: 'payments',
    capabilities: 'Payments/subscriptions/invoices/webhooks/billing',
    automationLevel: 'AUTO',
    description: 'Process payments, manage subscriptions, and handle billing via Stripe.',
    icon: 'CreditCard',
    color: '#635BFF',
    sortOrder: 88,
  },
  {
    toolNumber: 89,
    name: 'PayPal',
    url: 'https://developer.paypal.com/docs/api',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'PAYPAL_CLIENT_ID', label: 'PayPal Client ID', isSecret: false },
      { key: 'PAYPAL_CLIENT_SECRET', label: 'PayPal Client Secret', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'payment',
    subcategory: 'payments',
    capabilities: 'Payments/orders/subscriptions/webhooks/refunds',
    automationLevel: 'AUTO',
    description: 'Process payments and manage orders via PayPal API.',
    icon: 'Wallet',
    color: '#003087',
    sortOrder: 89,
  },
  {
    toolNumber: 90,
    name: 'bKash',
    url: 'https://developer.bka.sh',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'BKASH_APP_KEY', label: 'bKash App Key', isSecret: true },
      { key: 'BKASH_APP_SECRET', label: 'bKash App Secret', isSecret: true },
      { key: 'BKASH_USERNAME', label: 'bKash Username', isSecret: false },
      { key: 'BKASH_PASSWORD', label: 'bKash Password', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'payment',
    subcategory: 'payments',
    capabilities: 'Mobile payments/bKash wallet/payment gateway/Bangladesh',
    automationLevel: 'AUTO',
    description: 'Process mobile payments via bKash payment gateway for Bangladesh market.',
    icon: 'Banknote',
    color: '#E2136E',
    sortOrder: 90,
  },
  {
    toolNumber: 91,
    name: 'SSLCOMMERZ',
    url: 'https://developer.sslcommerz.com',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'SSLCOMMERZ_STORE_ID', label: 'SSLCommerz Store ID', isSecret: false },
      { key: 'SSLCOMMERZ_STORE_PASSWORD', label: 'SSLCommerz Store Password', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'payment',
    subcategory: 'payments',
    capabilities: 'Payment gateway/Bangladesh/multi-bank/visa/mastercard',
    automationLevel: 'AUTO',
    description: 'Process payments via SSLCommerz payment gateway supporting Bangladesh banks.',
    icon: 'ShieldCheck',
    color: '#F7941D',
    sortOrder: 91,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TRACKING (4 tools, 092–095)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 92,
    name: 'Google Tag Manager',
    url: 'https://tagmanager.google.com',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
      { key: 'GTM_CONTAINER_ID', label: 'GTM Container ID', isSecret: false },
    ]),
    connectionType: 'api',
    category: 'tracking',
    subcategory: 'tracking',
    capabilities: 'Tag management/tracking pixels/custom events/data layer',
    automationLevel: 'AUTO',
    description: 'Manage tracking tags and pixels via Google Tag Manager API.',
    icon: 'Tag',
    color: '#4285F4',
    sortOrder: 92,
  },
  {
    toolNumber: 93,
    name: 'Meta Pixel',
    url: 'https://developers.facebook.com/docs/meta-pixel',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'META_PIXEL_ID', label: 'Meta Pixel ID', isSecret: false },
      { key: 'META_CONVERSION_API_TOKEN', label: 'Conversion API Token', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'tracking',
    subcategory: 'tracking',
    capabilities: 'Event tracking/conversion tracking/custom audiences/optimization',
    automationLevel: 'AUTO',
    description: 'Install and configure Meta Pixel for conversion tracking and audience building.',
    icon: 'Eye',
    color: '#1877F2',
    sortOrder: 93,
  },
  {
    toolNumber: 94,
    name: 'TikTok Pixel',
    url: 'https://ads.tiktok.com/help/article/tiktok-pixel-overview',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'TIKTOK_PIXEL_ID', label: 'TikTok Pixel ID', isSecret: false },
      { key: 'TIKTOK_EVENT_API_TOKEN', label: 'Event API Token', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'tracking',
    subcategory: 'tracking',
    capabilities: 'Event tracking/conversion tracking/optimization/audiences',
    automationLevel: 'AUTO',
    description: 'Install and configure TikTok Pixel for conversion tracking and ad optimization.',
    icon: 'Eye',
    color: '#000000',
    sortOrder: 94,
  },
  {
    toolNumber: 95,
    name: 'LinkedIn Insight Tag',
    url: 'https://www.linkedin.com/help/linkedin/answer/a4603585',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'LINKEDIN_PARTNER_ID', label: 'LinkedIn Partner ID', isSecret: false },
      { key: 'LINKEDIN_CONVERSION_ID', label: 'LinkedIn Conversion ID', isSecret: false },
    ]),
    connectionType: 'api',
    category: 'tracking',
    subcategory: 'tracking',
    capabilities: 'Insight tracking/conversion tracking/audience building/retargeting',
    automationLevel: 'AUTO',
    description: 'Install LinkedIn Insight Tag for website tracking and conversion measurement.',
    icon: 'Target',
    color: '#0A66C2',
    sortOrder: 95,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SECURITY (3 tools, 096–098)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 96,
    name: 'Cloudflare',
    url: 'https://developers.cloudflare.com/api',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'CLOUDFLARE_API_TOKEN', label: 'Cloudflare API Token', isSecret: true },
      { key: 'CLOUDFLARE_ZONE_ID', label: 'Cloudflare Zone ID', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'security',
    subcategory: 'dns_security',
    capabilities: 'DNS/SSL/CDN/firewall/bot management/DDoS protection',
    automationLevel: 'AUTO',
    description: 'Manage DNS, SSL, CDN, and security settings via Cloudflare API.',
    icon: 'Shield',
    color: '#F48120',
    sortOrder: 96,
  },
  {
    toolNumber: 97,
    name: 'Google reCAPTCHA',
    url: 'https://www.google.com/recaptcha/admin',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'RECAPTCHA_SITE_KEY', label: 'reCAPTCHA Site Key', isSecret: false },
      { key: 'RECAPTCHA_SECRET_KEY', label: 'reCAPTCHA Secret Key', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'security',
    subcategory: 'bot_protection',
    capabilities: 'Bot protection/spam prevention/form security/score analysis',
    automationLevel: 'AUTO',
    description: 'Protect forms and pages from bots using Google reCAPTCHA v2/v3.',
    icon: 'ShieldCheck',
    color: '#4285F4',
    sortOrder: 97,
  },
  {
    toolNumber: 98,
    name: 'hCaptcha',
    url: 'https://docs.hcaptcha.com',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'HCAPTCHA_SITE_KEY', label: 'hCaptcha Site Key', isSecret: false },
      { key: 'HCAPTCHA_SECRET_KEY', label: 'hCaptcha Secret Key', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'security',
    subcategory: 'bot_protection',
    capabilities: 'Bot protection/privacy-focused captcha/enterprise security',
    automationLevel: 'AUTO',
    description: 'Privacy-focused bot protection with hCaptcha for form and page security.',
    icon: 'ShieldCheck',
    color: '#1254D1',
    sortOrder: 98,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NOTIFICATION (2 tools, 099–100)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 99,
    name: 'Firebase',
    url: 'https://firebase.google.com/docs',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'FIREBASE_PROJECT_ID', label: 'Firebase Project ID', isSecret: false },
      { key: 'FIREBASE_SERVICE_ACCOUNT_KEY', label: 'Firebase Service Account Key', isSecret: true },
      { key: 'FIREBASE_WEB_API_KEY', label: 'Firebase Web API Key', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'notification',
    subcategory: 'auth_notifications',
    capabilities: 'Push notifications/auth/realtime database/cloud messaging/analytics',
    automationLevel: 'AUTO',
    description: 'Send push notifications, manage auth, and access Firebase Cloud Messaging.',
    icon: 'Bell',
    color: '#FFCA28',
    sortOrder: 99,
  },
  {
    toolNumber: 100,
    name: 'OneSignal',
    url: 'https://documentation.onesignal.com/docs/api-reference',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'ONESIGNAL_APP_ID', label: 'OneSignal App ID', isSecret: false },
      { key: 'ONESIGNAL_REST_API_KEY', label: 'OneSignal REST API Key', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'notification',
    subcategory: 'push_notifications',
    capabilities: 'Push notifications/segments/A-B testing/delivery',
    automationLevel: 'AUTO',
    description: 'Send and manage push notifications across platforms with OneSignal.',
    icon: 'BellRing',
    color: '#EE4B2B',
    sortOrder: 100,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // INFRASTRUCTURE (4 tools, 101–104)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 101,
    name: 'MinIO',
    url: 'https://min.io/docs/minio/linux/developers/minio-drivers.html',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'MINIO_ENDPOINT', label: 'MinIO Endpoint', isSecret: false },
      { key: 'MINIO_ACCESS_KEY', label: 'MinIO Access Key', isSecret: true },
      { key: 'MINIO_SECRET_KEY', label: 'MinIO Secret Key', isSecret: true },
      { key: 'MINIO_BUCKET', label: 'MinIO Bucket Name', isSecret: false },
    ]),
    connectionType: 'api',
    category: 'infrastructure',
    subcategory: 'storage',
    capabilities: 'Object storage/S3-compatible/file upload/download/buckets',
    automationLevel: 'AUTO',
    description: 'S3-compatible object storage via MinIO for file management.',
    icon: 'HardDrive',
    color: '#C72C48',
    sortOrder: 101,
  },
  {
    toolNumber: 102,
    name: 'PostgreSQL',
    url: 'https://www.postgresql.org/docs',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'POSTGRES_HOST', label: 'PostgreSQL Host', isSecret: false },
      { key: 'POSTGRES_PORT', label: 'PostgreSQL Port', isSecret: false },
      { key: 'POSTGRES_USER', label: 'PostgreSQL Username', isSecret: false },
      { key: 'POSTGRES_PASSWORD', label: 'PostgreSQL Password', isSecret: true },
      { key: 'POSTGRES_DATABASE', label: 'PostgreSQL Database', isSecret: false },
    ]),
    connectionType: 'database',
    category: 'infrastructure',
    subcategory: 'database',
    capabilities: 'Relational database/queries/transactions/migrations',
    automationLevel: 'AUTO',
    description: 'Connect to PostgreSQL database for advanced data storage and queries.',
    icon: 'Database',
    color: '#336791',
    sortOrder: 102,
  },
  {
    toolNumber: 103,
    name: 'MySQL',
    url: 'https://dev.mysql.com/doc',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'MYSQL_HOST', label: 'MySQL Host', isSecret: false },
      { key: 'MYSQL_PORT', label: 'MySQL Port', isSecret: false },
      { key: 'MYSQL_USER', label: 'MySQL Username', isSecret: false },
      { key: 'MYSQL_PASSWORD', label: 'MySQL Password', isSecret: true },
      { key: 'MYSQL_DATABASE', label: 'MySQL Database', isSecret: false },
    ]),
    connectionType: 'database',
    category: 'infrastructure',
    subcategory: 'database',
    capabilities: 'Relational database/queries/replication/cluster',
    automationLevel: 'AUTO',
    description: 'Connect to MySQL database for data storage and management.',
    icon: 'Database',
    color: '#4479A1',
    sortOrder: 103,
  },
  {
    toolNumber: 104,
    name: 'Redis',
    url: 'https://redis.io/documentation',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'REDIS_URL', label: 'Redis URL', isSecret: true },
      { key: 'REDIS_PASSWORD', label: 'Redis Password', isSecret: true },
    ]),
    connectionType: 'redis',
    category: 'infrastructure',
    subcategory: 'cache',
    capabilities: 'In-memory cache/sessions/rate limiting/pub-sub/queues',
    automationLevel: 'AUTO',
    description: 'In-memory data store for caching, sessions, and real-time features.',
    icon: 'Server',
    color: '#DC382D',
    sortOrder: 104,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEVOPS/AUTOMATION (7 tools, 105–111)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 105,
    name: 'n8n',
    url: 'https://docs.n8n.io/api',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'N8N_API_KEY', label: 'n8n API Key', isSecret: true },
      { key: 'N8N_BASE_URL', label: 'n8n Base URL', isSecret: false },
    ]),
    connectionType: 'automation',
    category: 'devops',
    subcategory: 'automation',
    capabilities: 'Workflow automation/integrations/webhooks/data transformation',
    automationLevel: 'AUTO',
    description: 'Create and manage automation workflows via n8n API.',
    icon: 'Workflow',
    color: '#FF6D5A',
    sortOrder: 105,
  },
  {
    toolNumber: 106,
    name: 'GitHub',
    url: 'https://docs.github.com/en/rest',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GITHUB_PAT', label: 'GitHub Personal Access Token', isSecret: true },
      { key: 'GITHUB_CLIENT_ID', label: 'GitHub Client ID', isSecret: false },
      { key: 'GITHUB_CLIENT_SECRET', label: 'GitHub Client Secret', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'devops',
    subcategory: 'code_automation',
    capabilities: 'Repository management/CI-CD/issues/actions/webhooks',
    automationLevel: 'AUTO',
    description: 'Manage GitHub repositories, issues, and automate via GitHub Actions.',
    icon: 'Github',
    color: '#000000',
    sortOrder: 106,
  },
  {
    toolNumber: 107,
    name: 'Sentry',
    url: 'https://docs.sentry.io/api',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'SENTRY_DSN', label: 'Sentry DSN', isSecret: true },
      { key: 'SENTRY_AUTH_TOKEN', label: 'Sentry Auth Token', isSecret: true },
      { key: 'SENTRY_ORG_SLUG', label: 'Sentry Organization Slug', isSecret: false },
    ]),
    connectionType: 'rest_api',
    category: 'devops',
    subcategory: 'error_monitoring',
    capabilities: 'Error tracking/performance monitoring/issue management/releases',
    automationLevel: 'AUTO',
    description: 'Monitor application errors and performance via Sentry API.',
    icon: 'AlertTriangle',
    color: '#362D59',
    sortOrder: 107,
  },
  {
    toolNumber: 108,
    name: 'Slack',
    url: 'https://api.slack.com/docs',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'SLACK_BOT_TOKEN', label: 'Slack Bot Token', isSecret: true },
      { key: 'SLACK_CLIENT_ID', label: 'Slack Client ID', isSecret: false },
      { key: 'SLACK_CLIENT_SECRET', label: 'Slack Client Secret', isSecret: true },
      { key: 'SLACK_SIGNING_SECRET', label: 'Slack Signing Secret', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'devops',
    subcategory: 'internal_alerts',
    capabilities: 'Messaging/channels/alerts/integrations/workflow notifications',
    automationLevel: 'AUTO',
    description: 'Send alerts and notifications to Slack channels via Bot API.',
    icon: 'Hash',
    color: '#4A154B',
    sortOrder: 108,
  },
  {
    toolNumber: 109,
    name: 'Discord (Notifications)',
    url: 'https://discord.com/developers/docs',
    authType: 'bot_token',
    requiredCredentials: creds([
      { key: 'DISCORD_NOTIFICATION_BOT_TOKEN', label: 'Discord Notification Bot Token', isSecret: true },
      { key: 'DISCORD_NOTIFICATION_WEBHOOK_URL', label: 'Discord Webhook URL', isSecret: true },
    ]),
    connectionType: 'webhook',
    category: 'devops',
    subcategory: 'notifications',
    capabilities: 'Notifications/alerts/embed messages/channel management',
    automationLevel: 'AUTO',
    description: 'Send notifications and alerts to Discord channels for devops monitoring.',
    icon: 'Bell',
    color: '#5865F2',
    sortOrder: 109,
  },
  {
    toolNumber: 110,
    name: 'Zapier',
    url: 'https://developer.zapier.com/docs',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'ZAPIER_API_KEY', label: 'Zapier API Key', isSecret: true },
    ]),
    connectionType: 'api',
    category: 'devops',
    subcategory: 'automation',
    capabilities: 'Workflow automation/5000+ app integrations/triggers/actions',
    automationLevel: 'AUTO',
    description: 'Automate workflows by connecting 5000+ apps via Zapier API.',
    icon: 'Zap',
    color: '#FF4A00',
    sortOrder: 110,
  },
  {
    toolNumber: 111,
    name: 'Make',
    url: 'https://www.make.com/en/developers',
    authType: 'api_key',
    requiredCredentials: creds([
      { key: 'MAKE_API_KEY', label: 'Make API Key', isSecret: true },
      { key: 'MAKE_WEBHOOK_URL', label: 'Make Webhook URL', isSecret: true },
    ]),
    connectionType: 'rest_api',
    category: 'devops',
    subcategory: 'automation',
    capabilities: 'Visual workflow automation/scenarios/webhooks/data transformation',
    automationLevel: 'AUTO',
    description: 'Build and manage automation scenarios with Make (formerly Integromat).',
    icon: 'Workflow',
    color: '#5D45DB',
    sortOrder: 111,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GOOGLE EXTENDED (1 tool, 112)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 112,
    name: 'Google Business Reviews',
    url: 'https://developers.google.com/my-business/reference/rest',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'GOOGLE_CLIENT_ID', label: 'Google Client ID', isSecret: false },
      { key: 'GOOGLE_CLIENT_SECRET', label: 'Google Client Secret', isSecret: true },
      { key: 'GOOGLE_BUSINESS_ACCOUNT_ID', label: 'Business Account ID', isSecret: false },
    ]),
    connectionType: 'api',
    category: 'google',
    subcategory: 'reputation',
    capabilities: 'Review management/rating monitoring/reply/reputation tracking',
    automationLevel: 'LIMITED',
    description: 'Monitor and reply to Google Business reviews for reputation management.',
    icon: 'Star',
    color: '#FBBC04',
    sortOrder: 112,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // META MESSAGING (2 tools, 113–114)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 113,
    name: 'Facebook Messenger',
    url: 'https://developers.facebook.com/docs/messenger-platform',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'FACEBOOK_APP_ID', label: 'Facebook App ID', isSecret: false },
      { key: 'FACEBOOK_APP_SECRET', label: 'Facebook App Secret', isSecret: true },
      { key: 'FACEBOOK_PAGE_ACCESS_TOKEN', label: 'Page Access Token', isSecret: true },
    ]),
    connectionType: 'graph_api',
    category: 'meta',
    subcategory: 'messaging',
    capabilities: 'Messenger bots/chat/quick replies/persistent menu/broadcast',
    automationLevel: 'AUTO',
    description: 'Send and receive Facebook Messenger messages for customer engagement.',
    icon: 'MessageCircle',
    color: '#1877F2',
    sortOrder: 113,
  },
  {
    toolNumber: 114,
    name: 'Instagram Direct',
    url: 'https://developers.facebook.com/docs/instagram-api/guides/messaging',
    authType: 'oauth2',
    requiredCredentials: creds([
      { key: 'FACEBOOK_APP_ID', label: 'Facebook App ID', isSecret: false },
      { key: 'FACEBOOK_APP_SECRET', label: 'Facebook App Secret', isSecret: true },
      { key: 'FACEBOOK_PAGE_ACCESS_TOKEN', label: 'Page Access Token', isSecret: true },
    ]),
    connectionType: 'graph_api',
    category: 'meta',
    subcategory: 'messaging',
    capabilities: 'Instagram DM/chat/replies/media sharing/automated responses',
    automationLevel: 'AUTO',
    description: 'Send and receive Instagram Direct Messages for customer engagement.',
    icon: 'MessageCircle',
    color: '#E4405F',
    sortOrder: 114,
  },

  // ALO INTERNAL (5 tools, 116–120)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    toolNumber: 116,
    name: 'ALO Website Lead Form',
    url: 'https://marketingos.ai',
    authType: 'internal',
    requiredCredentials: creds([]),
    connectionType: 'internal',
    category: 'alo_internal',
    subcategory: 'direct_leads',
    capabilities: 'Lead capture/form submissions/contact requests/direct inquiries',
    automationLevel: 'AUTO',
    description: 'Capture leads directly from the ALO MarketingOS website lead forms.',
    icon: 'FileText',
    color: '#F97316',
    sortOrder: 116,
  },
  {
    toolNumber: 117,
    name: 'ALO AI University Finder',
    url: 'https://marketingos.ai',
    authType: 'internal',
    requiredCredentials: creds([]),
    connectionType: 'internal',
    category: 'alo_internal',
    subcategory: 'qualified_leads',
    capabilities: 'AI-powered university matching/preference analysis/lead qualification',
    automationLevel: 'AUTO',
    description: 'AI-powered university finder that generates qualified leads through preference analysis.',
    icon: 'GraduationCap',
    color: '#F97316',
    sortOrder: 117,
  },
  {
    toolNumber: 118,
    name: 'ALO Scholarship Finder',
    url: 'https://marketingos.ai',
    authType: 'internal',
    requiredCredentials: creds([]),
    connectionType: 'internal',
    category: 'alo_internal',
    subcategory: 'qualified_leads',
    capabilities: 'Scholarship matching/eligibility check/lead qualification',
    automationLevel: 'AUTO',
    description: 'AI-powered scholarship finder that matches students with relevant funding opportunities.',
    icon: 'Award',
    color: '#F97316',
    sortOrder: 118,
  },
  {
    toolNumber: 119,
    name: 'ALO Eligibility Checker',
    url: 'https://marketingos.ai',
    authType: 'internal',
    requiredCredentials: creds([]),
    connectionType: 'internal',
    category: 'alo_internal',
    subcategory: 'qualified_leads',
    capabilities: 'Eligibility verification/document check/profile assessment/lead scoring',
    automationLevel: 'AUTO',
    description: 'Automated eligibility checker that scores and qualifies student leads.',
    icon: 'CheckCircle',
    color: '#F97316',
    sortOrder: 119,
]

// ── Seed Function ────────────────────────────────────────────────────────────

async function seedTools() {
  console.log(`Seeding ${TOOLS.length} tool definitions...`)
  console.log('')

  let created = 0
  let updated = 0

  for (const tool of TOOLS) {
    const result = await prisma.toolDefinition.upsert({
      where: { toolNumber: tool.toolNumber },
      update: {
        name: tool.name,
        url: tool.url,
        authType: tool.authType,
        requiredCredentials: tool.requiredCredentials,
        connectionType: tool.connectionType,
        category: tool.category,
        subcategory: tool.subcategory,
        capabilities: tool.capabilities,
        automationLevel: tool.automationLevel,
        description: tool.description,
        icon: tool.icon,
        color: tool.color,
        sortOrder: tool.sortOrder,
        isEnabled: true,
      },
      create: {
        toolNumber: tool.toolNumber,
        name: tool.name,
        url: tool.url,
        authType: tool.authType,
        requiredCredentials: tool.requiredCredentials,
        connectionType: tool.connectionType,
        category: tool.category,
        subcategory: tool.subcategory,
        capabilities: tool.capabilities,
        automationLevel: tool.automationLevel,
        description: tool.description,
        icon: tool.icon,
        color: tool.color,
        sortOrder: tool.sortOrder,
        isEnabled: true,
      },
    })

    // If id starts with 'cuid' pattern (new record), count as created.
    // We can detect by checking if it was just now inserted vs already existed.
    // Prisma upsert doesn't tell us directly, so we track via the count.
    if (result) {
      // Since we can't easily distinguish, we log the tool number.
      process.stdout.write(`  ✓ Tool ${String(tool.toolNumber).padStart(3, '0')}: ${tool.name}\n`)
    }
  }

  console.log('')
  console.log(`✅ Successfully seeded ${TOOLS.length} tool definitions into the database.`)

  // Print category summary
  const categoryCounts = new Map<string, number>()
  for (const tool of TOOLS) {
    const count = categoryCounts.get(tool.category) ?? 0
    categoryCounts.set(tool.category, count + 1)
  }

  console.log('')
  console.log('Category Summary:')
  for (const entry of Array.from(categoryCounts.entries())) {
    const [category, count] = entry
    console.log(`  ${category.padEnd(20)} ${count} tools`)
  }
  console.log('')
  console.log(`  ${'TOTAL'.padEnd(20)} ${TOOLS.length} tools`)
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  try {
    await seedTools()
  } catch (error) {
    console.error('❌ Failed to seed tool definitions:', error)
    process.exit(1)
  } finally {
    await prisma.$disconnect()
  }
}

main()
